name: Update latest tag according to mavp2p
on:
  # See: https://jasonet.co/posts/scheduled-actions/
  schedule:
    # Trigger tags update twice per day
    - cron: "0 */12 * * *"

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
        # We need this to trigger another workflows
        #   See: https://github.com/orgs/community/discussions/25617
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      # Retrieve the latest tag to use as mavp2p release tag.
      - name: Update tags
        run: ./update-tags.sh
      # Push tags
      - name: Push tags
        run: git push --tags
